### ISSUE TITLE
new fluidtime logo

### ISSUE THREAD

**Issue by rompic** [tomheller/pie.fh-hagenberg.at#1]
fluidtime has a new logo see http://fluidtime.com/de/

**Comment by rompic** [comment]
also see http://pie.fh-hagenberg.at/projekte/research-projects/bikenplay/

**Comment by tomheller** [comment]
Thanks @rompic. I will take care of this as soon as possible.

**Comment by tomheller** [comment]
Logo updated by b48eb28
